# Generated by Django 2.2 on 2023-03-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Goods',
        ),
    ]
